"$schema" = "https://raw.githubusercontent.com/orpos/kaledis/refs/heads/main/static/kaledis.schema.json"
# Used for macos and android apps
game_id = "com.game.test"
project_name = "test"
love = "11.5"
detect_modules = true

[polyfill]
location = "./dalbit-polyfill"

[layout]
code = "src"
